language: python
python:
  - "2.7"
  - "3.4"
  - "3.3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

install:
  - pip install -r requirements-test.txt

script:
  - python -m coverage run run_tests.py
  - python -m coverage report -m 2>&1

after_success:
  coveralls